
// This file has been generated by the GUI designer. Do not modify.
namespace ICSharpCode.NRefactory.GtkDemo
{
	public partial class IndentEngineWindow
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.ScrolledWindow scrolledwindow1;
		private global::Gtk.TextView textviewIndent;
		private global::Gtk.Label label4;
		private global::Gtk.HBox hbox1;
		private global::Gtk.VBox vbox1;
		private global::Gtk.Label label1;
		private global::Gtk.Label label2;
		private global::Gtk.Label label3;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Label lblCurrentState;
		private global::Gtk.Label lblThisLineIndent;
		private global::Gtk.Label lblNextLineIndent;
		private global::Gtk.VBox vbox6;
		private global::Gtk.Label label7;
		private global::Gtk.Label label8;
		private global::Gtk.Label label9;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label lblIsLineStart;
		private global::Gtk.Label lblNeedsReindent;
		private global::Gtk.Label lblCurrentIndent;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label lblLocation;
		private global::Gtk.Button btnReset;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ICSharpCode.NRefactory.GtkDemo.IndentEngineWindow
			this.Name = "ICSharpCode.NRefactory.GtkDemo.IndentEngineWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("C# indent");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ICSharpCode.NRefactory.GtkDemo.IndentEngineWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.textviewIndent = new global::Gtk.TextView ();
			this.textviewIndent.CanFocus = true;
			this.textviewIndent.Name = "textviewIndent";
			this.textviewIndent.Justification = ((global::Gtk.Justification)(3));
			this.scrolledwindow1.Add (this.textviewIndent);
			this.vbox2.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.scrolledwindow1]));
			w2.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"red\" size=\"smaller\">This demo does NOT support inserting or del" +
				"eting of chars. Please write only at the end of the textview.</span>");
			this.label4.UseMarkup = true;
			this.vbox2.Add (this.label4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label4]));
			w3.Position = 1;
			w3.Expand = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Current state: ");
			this.vbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
			w4.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("This line indent: ");
			this.vbox1.Add (this.label2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label2]));
			w5.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Next line indent: ");
			this.vbox1.Add (this.label3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label3]));
			w6.Position = 2;
			this.hbox1.Add (this.vbox1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			w7.Padding = ((uint)(20));
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.lblCurrentState = new global::Gtk.Label ();
			this.lblCurrentState.Name = "lblCurrentState";
			this.lblCurrentState.Xalign = 0F;
			this.lblCurrentState.LabelProp = global::Mono.Unix.Catalog.GetString ("GlobalBody");
			this.lblCurrentState.UseMarkup = true;
			this.vbox5.Add (this.lblCurrentState);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.lblCurrentState]));
			w8.Position = 0;
			// Container child vbox5.Gtk.Box+BoxChild
			this.lblThisLineIndent = new global::Gtk.Label ();
			this.lblThisLineIndent.Name = "lblThisLineIndent";
			this.lblThisLineIndent.Xalign = 0F;
			this.lblThisLineIndent.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.vbox5.Add (this.lblThisLineIndent);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.lblThisLineIndent]));
			w9.Position = 1;
			// Container child vbox5.Gtk.Box+BoxChild
			this.lblNextLineIndent = new global::Gtk.Label ();
			this.lblNextLineIndent.Name = "lblNextLineIndent";
			this.lblNextLineIndent.Xalign = 0F;
			this.lblNextLineIndent.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.vbox5.Add (this.lblNextLineIndent);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.lblNextLineIndent]));
			w10.Position = 2;
			this.hbox1.Add (this.vbox5);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox5]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			w11.Padding = ((uint)(20));
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Is line start: ");
			this.vbox6.Add (this.label7);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label7]));
			w12.Position = 0;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xalign = 0F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Needs reindent: ");
			this.vbox6.Add (this.label8);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label8]));
			w13.Position = 1;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.Xalign = 0F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Current indent: ");
			this.vbox6.Add (this.label9);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label9]));
			w14.Position = 2;
			this.hbox1.Add (this.vbox6);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox6]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			w15.Padding = ((uint)(20));
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.lblIsLineStart = new global::Gtk.Label ();
			this.lblIsLineStart.Name = "lblIsLineStart";
			this.lblIsLineStart.Xalign = 0F;
			this.lblIsLineStart.LabelProp = global::Mono.Unix.Catalog.GetString ("Yes");
			this.vbox3.Add (this.lblIsLineStart);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lblIsLineStart]));
			w16.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.lblNeedsReindent = new global::Gtk.Label ();
			this.lblNeedsReindent.Name = "lblNeedsReindent";
			this.lblNeedsReindent.Xalign = 0F;
			this.lblNeedsReindent.LabelProp = global::Mono.Unix.Catalog.GetString ("False");
			this.vbox3.Add (this.lblNeedsReindent);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lblNeedsReindent]));
			w17.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.lblCurrentIndent = new global::Gtk.Label ();
			this.lblCurrentIndent.Name = "lblCurrentIndent";
			this.lblCurrentIndent.Xalign = 0F;
			this.lblCurrentIndent.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.vbox3.Add (this.lblCurrentIndent);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lblCurrentIndent]));
			w18.Position = 2;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
			w19.Position = 3;
			w19.Expand = false;
			w19.Fill = false;
			w19.Padding = ((uint)(20));
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.lblLocation = new global::Gtk.Label ();
			this.lblLocation.Name = "lblLocation";
			this.lblLocation.LabelProp = global::Mono.Unix.Catalog.GetString ("(Line 1, Col 1)");
			this.vbox4.Add (this.lblLocation);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblLocation]));
			w20.Position = 0;
			// Container child vbox4.Gtk.Box+BoxChild
			this.btnReset = new global::Gtk.Button ();
			this.btnReset.CanFocus = true;
			this.btnReset.Name = "btnReset";
			this.btnReset.UseUnderline = true;
			this.btnReset.Label = global::Mono.Unix.Catalog.GetString ("Reset");
			this.vbox4.Add (this.btnReset);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.btnReset]));
			w21.Position = 1;
			this.hbox1.Add (this.vbox4);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox4]));
			w22.Position = 4;
			w22.Expand = false;
			w22.Fill = false;
			w22.Padding = ((uint)(25));
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			w23.Padding = ((uint)(10));
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 710;
			this.DefaultHeight = 735;
			this.Show ();
			this.textviewIndent.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnTextviewIndentKeyPressEvent);
			this.btnReset.Clicked += new global::System.EventHandler (this.OnBtnResetClicked);
		}
	}
}
